version: '3.8'

services:
  pcf-component:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: ["./scripts/entrypoint.sh"]